### PR TITLE
feat(build): add autotools support

### PR DESCRIPTION
**Pull request by fzipi**
Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

This one add autotooling to the mix. Tried to catch all possible scenarios, but please let me know if someone was left out.

- removed ubuntu 16.04 from the CI run, because it is eol
- added files to gitignore
- moved library version outside of libinjection_sqli.c file, and now it is generated by tooling and included
- added pkgconfig file

### CODE REVIEW

**Comment by fzipi** [comment]
@zimmerle Finally could make it work with all the changes. What do you think on this one?

**Comment by fzipi** [comment]
@migueldemoura @jpereira Hey! Don't know who of you have access to the repo to merge this, or at least comment/take a look.

**Comment by migueldemoura** [comment]
I'm afraid I don't have merge permissions, can you check, @zimmerle?

**Review by migueldemoura — APPROVED** [review]

**Comment by fzipi** [comment]
Merging following approval.

**Comment by odeneriksson** [comment]
Had a quick look at this today and you need to "echo 3.10.0 > .tarball-version" for this to work. Maybe this is handled by a script to generate the tar ball release. The SONAME seems odd. As this library never had it you should probably set it to zero, like:

LT_CURRENT=0
LT_REVISION=0
LT_AGE=0

It would be nice to have the binaries and test data installed as well.

**Comment by fzipi** [comment]
Yes! I have a follow up pr with those fixes and a couple more. Thanks for taking a look!

**Pull request merged**
