### PR TITLE
Fix -Wstrict-prototypes warnings

### PR DESCRIPTION
**Pull request by veeshi**

### CODE REVIEW

**Comment by fzipi** [comment]
Hi @veeshi ! Can you rebase to latest and push again?

**Comment by fzipi** [comment]
@veeshi ping again?

**Comment by veeshi** [comment]
Apologies, I've merged the latest changes

**Review by migueldemoura — APPROVED** [review]

**Review by fzipi — APPROVED** [review]
LGTM! Thanks for your contribution!

**Pull request merged**
