### PR TITLE
feat(py3): update build syntax to py3

### PR DESCRIPTION
**Pull request by fzipi**
Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

Updates build syntax to py3.

### CODE REVIEW

**Comment by zimmerle** [comment]
Thanks @fzipi!

**Comment by fzipi** [comment]
What do you think, should this one be merged?

**Comment by migueldemoura** [comment]
Not sure what we're doing with the changelog, but other than that it lgtm.

**Comment by fzipi** [comment]
@migueldemoura Nothing in particular, just adding what was done. Will remove.

**Comment by fzipi** [comment]
@migueldemoura Removed.

**Review by zimmerle — COMMENTED** [review]
all fine :) :+1:

**Pull request merged**
